### ISSUE TITLE
Associated projects

### ISSUE THREAD

**Issue by jdsika** [openMSL/.github#15]
I like how esmini is displaying other projects in their readme rather prominently and showing the interaction with e.g. OSI as a related standard.
I feel that OpenMSL is turning into a node in a network of open source resources and specifications representing the interaction and best practices in the space. I would like to make the users aware of this fact and put this information on display. Any ideas?

**Comment by ClemensLinnhoff** [comment]
We could do a "Related Work" page and link it on the .github profile. I think it would be best to put in on a separate page, as it would be too much directly on the profile. But since this will be for the entire organization, it would make sense to link it there.

**Comment by ClemensLinnhoff** [comment]
I just created a draft. We can continue the discussion in the PR.
